### ISSUE TITLE
Unable to find a specification for `FBSKCoreKit (~> 8.0.0)` depended upon by `CapacitorPluginFacebookAnalytics`

### ISSUE THREAD

**Issue by AbhishekShrivas** [SpellChucker/capacitor-plugin-facebook-analytics#5]
npx cap sync after npm install giving this error => 
Unable to find a specification for `FBSKCoreKit (~> 8.0.0)` depended upon by `CapacitorPluginFacebookAnalytics`
You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by rennerwins** [comment]
I'm facing the same issue

**Comment by kedarguy** [comment]
I added a fix with #6

**Comment by reubenwedson** [comment]
How long takes until this is merged? @kedarguy @SpellChucker

**Comment by SpellChucker** [comment]
Issue should be fixed in 0.0.4

**Comment by reubenwedson** [comment]
> Issue should be fixed in 0.0.4

![bitmoji](https://sdk.bitmoji.com/render/panel/044e0f9d-15f3-4931-bb42-f775da9fcf0e-266205a9-6cf7-45fa-bee8-fd6f7cdd1f8a-v1.png?transparent=1&palette=1&width=246)
